feat: new release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -11,7 +11,7 @@ jobs:
     name: Release
     runs-on: ubuntu-latest
     permissions:
-        contents: write
+      contents: write
     steps:
       - name: Dump GitHub context
         env:
@@ -19,11 +19,41 @@ jobs:
         run: echo "$GITHUB_CONTEXT"
 
       - uses: actions/checkout@v4.2.2
+        with: 
+          fetch-depth: 0
 
       - uses: actions/setup-node@v4
         with:
           node-version: lts/*
 
+      - name: Configure Git
+        run: |
+          git config user.name "CI Bot"
+          git config user.email "ci@example.com"
+
+      - name: merge main into current branch
+        run: |
+          # Determine the current branch name
+          current_branch=$(git rev-parse --abbrev-ref HEAD)
+          echo "Processing branch: $current_branch"
+          
+          # Check if origin/main is ahead of the current branch
+          updates=$(git rev-list HEAD..origin/main --count)
+          echo "Updates available: $updates"
+          if [ "$updates" -gt 0 ]; then
+            git config pull.rebase false
+            git pull origin main
+            echo "Attempting merge..."
+            if git merge origin/main; then
+              git push origin "$current_branch"
+            else
+              echo "merge failed for branch '$current_branch' (merge conflicts may exist) - please resolve manually."
+              exit 1
+            fi
+          else
+            echo "Branch '$current_branch' is up-to-date with origin/main. No merge required."
+          fi
+      
       - name: Configure Semantic Release
         run: |
           echo '{
@@ -38,7 +68,8 @@ jobs:
                 "prerelease": "rc"
               }
             ],
-            "plugins": [
+            "plugins": 
+            [
               "@semantic-release/commit-analyzer",
               "@semantic-release/release-notes-generator",
               "@semantic-release/github"
@@ -50,48 +81,9 @@ jobs:
         uses: cycjimmy/semantic-release-action@v4
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NPM_TOKEN: ${{ secrets.ALL_PACKAGE_TOKEN }}        
 
       - name: Dump release outputs
         env:
           RELEASE_OUTPUTS: ${{ toJson(steps.semantic.outputs) }}
         run: echo "$RELEASE_OUTPUTS"
-          
-  merge:
-    name: Merge main into develop and release
-    runs-on: ubuntu-latest
-    needs: release
-    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
-    permissions:
-        contents: write
-    steps:
-      - uses: actions/checkout@v4.2.2
-
-      - name: Fetch all branches
-        run: git fetch --all
-
-      - name: configure git
-        run: |
-          git config --global user.email ""
-          git config --global user.name "GitHub Actions"
- 
-      - name: Merge main into develop
-        run: |
-          if git ls-remote --exit-code --heads origin develop; then
-            git checkout develop
-          else
-            git checkout -b develop origin/main
-          fi
-
-          git merge origin/main --no-edit --allow-unrelated-histories
-          git push origin develop
-
-      - name: Merge main into release
-        run: |
-          if git ls-remote --exit-code --heads origin release; then
-            git checkout release
-          else
-            git checkout -b release origin/main
-          fi
-
-          git merge origin/main --no-edit --allow-unrelated-histories
-          git push origin release
